Last modified date
LimeChain/RollupCodes pull request #38
Opened 2023-06-29 13:44 UTC by svetoslav-nikol0v

2023-06-30 08:46 UTC, Daniel-K-Ivanov commented
I think that it would be better if we extract the function for getting the last modified timestamp into a generic one placed in the `utils` folder.

f.e `computeLastModifiedTs(lastModifiedStorageKey, urlToFetchFrom, isRollupDetails)`

based on `isRollupDetails` determine where to look for the "last modified info in the response data of the query"
The function would return the last modified ts that should be later set in the storage

2023-07-04 10:22 UTC, svetoslav-nikol0v commented
I've created a hook that returns the modified date as a string in the required format as it's in the design. For future we can make the hook more flexible (I mean to add more props) if we need.

2023-07-05 07:26 UTC, Daniel-K-Ivanov requested changes
Can we rename the label to "Last Updated" and not "modified" it sounds better imo

2023-07-06 07:21 UTC, Daniel-K-Ivanov approved these changes

2023-07-06 07:21 UTC, merged