feat: update Optimism and Base information for the Cancun update
LimeChain/RollupCodes pull request #87
Opened 2024-03-26 15:26 UTC by dikel

Optimism support all Cancun EIPs except 4844. Also `BLOBBASEFEE` always returns 1. ([source](https://gov.optimism.io/t/upgrade-proposal-5-ecotone-network-upgrade/7669))

2024-03-27 07:54 UTC, Daniel-K-Ivanov requested changes
It seems that there are 2 new system contracts - - https://specs.optimism.io/protocol/predeploys.html#gaspriceoracle and https://specs.optimism.io/protocol/deposits.html#l1-attributes---ecotone

https://eips.ethereum.org/EIPS/eip-4788 is supported on OP/Base. This means that for all rollup that do not support the EIP we need to add a system contract which they do not support. EIP4788 isa system contract introduced on the Layer 1 and L2s may or may not support it. We should document it on all rollups

2024-03-29 09:51 UTC, dikel commented
Both system contracts are already added to the website. Additionally I checked the backtesting results of the [Delta upgrade](https://gov.optimism.io/t/final-upgrade-proposal-3-delta-network-upgrade/7310) and it doesn't lower the gas cost for L2->L1 messaging

2024-04-01 13:07 UTC, Daniel-K-Ivanov commented on src/docs/base.mdx
> +    | <Copy value="0x000F3df6D732807Ef1319fB7B8bB8522d0Beac02" label="0x000...c02" /> | <Reference label="BeaconRootsStorage" url="https://eips.ethereum.org/EIPS/eip-4788" /> | The contract has the f
```suggestion
    | <Copy value="0x000F3df6D732807Ef1319fB7B8bB8522d0Beac02" label="0x000...c02" /> | <Reference label="BeaconRootsStorage" url="https://eips.ethereum.org/EIPS/eip-4788" /> | The contract has the following differences compared to the L1: <br /><br /> 1. Data is updated with ~6-7 slots of delay compared to the L1 contract <br /> 2. `HISTORY_BUFFER_LENGTH ` is set to 1024 compared to 8191, meaning that the history is for ~3.41 hours compared to ~27 hours on L1 | The contract receives a timestamp and returns the beacon root associated with it <Modified /> |
```

2024-04-01 13:08 UTC, Daniel-K-Ivanov commented on src/docs/optimism.mdx
> +    | <Copy value="0x000F3df6D732807Ef1319fB7B8bB8522d0Beac02" label="0x000...c02" /> | <Reference label="BeaconRootsStorage" url="https://eips.ethereum.org/EIPS/eip-4788" /> | The contract has the f
```suggestion
 | <Copy value="0x000F3df6D732807Ef1319fB7B8bB8522d0Beac02" label="0x000...c02" /> | <Reference label="BeaconRootsStorage" url="https://eips.ethereum.org/EIPS/eip-4788" /> | The contract has the following differences compared to the L1: <br /><br /> 1. Data is updated with ~6-7 slots of delay <br /> 2. `HISTORY_BUFFER_LENGTH ` is set to 1024 compared to 8191, meaning that the history is for ~3.41 hours compared to ~27 hours on L1 | The contract receives a timestamp and returns the beacon root associated with it <Modified /> |
```

2024-04-01 13:28 UTC, Daniel-K-Ivanov approved these changes

2024-04-01 13:28 UTC, Daniel-K-Ivanov approved these changes

2024-04-01 13:28 UTC, merged